describe("form renders", () => {
    it("should render ts", () => {
        cy.visit("/anfrage/")
        cy.get('[action="#"] > :nth-child(3) > :nth-child(2)').click()
        // cy.get(".action-email").type("fake@email.com")
        cy.findByText("Vorname *")
            .click()
            .type("Jannis")
        cy.findByText("Nachname *")
            .click()
            .type("Wicke")
        cy.findByText("Geburtsdatum *")
            .click()
            .type("01.01.1990")
        cy.findByText("Straße und Hausnummer *")
            .click()
            .type("Bahnhofstr 1")
        cy.findByText("Postleitzahl *")
            .click()
            .type("12345")
        cy.findByText("Ort *")
            .click()
            .type("Berlin")
        cy.findByText("E-Mail *")
            .click()
            .type("test@test.com")
        cy.get('[action="#"] > :nth-child(12) > :nth-child(2)').click()
        cy.findByText("KFZ-Kennzeichen *")
            .click()
            .type("ABC 123")
        cy.get('[action="#"] > :nth-child(16) > :nth-child(2)').click()
        cy.get(":nth-child(19) > :nth-child(2)").click()
        cy.findByText("Hersteller *")
            .click()
            .type("BMW")
        cy.findByText("Typ *")
            .click()
            .type("3er")
        cy.findByText("Erstzulassung *")
            .click()
            .type("1958")
        cy.findByText("Versicherungssumme (Wiederbeschaffungswert) in € *")
            .click()
            .type("10000")
        cy.get(":nth-child(28) > select").select("bis 1.000 km")
        cy.findByText("Motorsträke in KW *")
            .click()
            .type("50")
        cy.get(":nth-child(32) > select").select("Makellos – Note 1")
        cy.get('[action="#"] > :nth-child(33) > :nth-child(2)').click()
        cy.get(":nth-child(34) > :nth-child(2)").click()
        cy.get(":nth-child(35) > select").select("eigenes Grundstück")
        cy.get('[action="#"] > :nth-child(36) > :nth-child(2)').click()
        cy.get(":nth-child(39) > :nth-child(3)").click()
        cy.get('[action="#"] > :nth-child(40) > :nth-child(2)').click()
        cy.get(":nth-child(41) > select").select("Nur Sie selbst")
        cy.get(":nth-child(42) > :nth-child(2)").click()
        cy.findByText("Ergänzende Angaben / Fragen")
            .click()
            .type("keine Fragen")
        cy.get(".terms-and-conditions").click()
    })
})
